startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT server:app --workers 2 --threads 2 --timeout 30
=======
    buildCommand: pip install -r backend/requirements.txt && cd backend && python init_db_render.py
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT server:app --workers 2 --threads 2 --timeout 30
