services:
  - type: web
    name: student-teacher-erp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.server:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
